cleanup

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -44,121 +44,128 @@ zopen_build()
         ./b2 headers
 }
 
+# Function to test Boost libraries
+build_and_test_boost() {
+    local test_dir="$1"
+    cd "$test_dir" || {
+        echo "Error: Failed to change directory to $test_dir"
+        return 1
+    }
+    "$ZOPEN_ROOT/boost/b2" --clean
+    "$ZOPEN_ROOT/boost/b2"
+    cd -
+}
+
 zopen_check()
 {
        echo `pwd`
-       cd $ZOPEN_ROOT/boost/libs/chrono/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
 
-       cd $ZOPEN_ROOT/boost/libs/thread/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
-       
-       cd $ZOPEN_ROOT/boost/libs/container/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/chrono/test"
 
-       cd $ZOPEN_ROOT/boost/libs/filesystem/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/thread/test"
 
-       cd $ZOPEN_ROOT/boost/libs/graph/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/container/test"
 
-       cd $ZOPEN_ROOT/boost/libs/serialization/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/filesystem/test"
 
-       cd $ZOPEN_ROOT/boost/libs/date_time/test
-       $ZOPEN_ROOT/boost/b2 --clean
-       $ZOPEN_ROOT/boost/b2
-       cd -
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/graph/test"
+
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/serialization/test"
+
+       build_and_test_boost "$ZOPEN_ROOT/boost/libs/date_time/test"
 }
+
+apply_patch() {
+    local patch_file="$1"
+    git apply "$patch_file"
+    if [ $? -ne 0 ]; then
+        echo "Error: git apply failed for $patch_file"
+        exit 1
+    fi
+}
+
+
 zopen_init()
 {
   # This runs after clone & regular patches are applied
   # and runs before bootstrap, configure, build
 
   #boostrap.sh path -> located at ./boost/bootstrap.sh
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/patches/fix_fileunix"
-  git apply $ZOPEN_ROOT/boostPatches/bootstrap.sh.patch
+  echo "In ZOPEN_INIT, applying patch to bootstrap"
+  apply_patch "$ZOPEN_ROOT/boostPatches/bootstrap.sh.patch"
 
   # aligned_alloc.hpp patch -> located at ./boost/libs/align/aligned_alloc.hpp
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/align.patch"
-  cd libs/align 
-  git apply $ZOPEN_ROOT/boostPatches/align.patch
+  echo "In ZOPEN_INIT, applying patch to lib - align"
+  cd libs/align
+  apply_patch "$ZOPEN_ROOT/boostPatches/align.patch"
   cd -
 
   # asio directory  patch -> located at ./boost/libs/asio
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/asio.patch"
+  echo "In ZOPEN_INIT, applying patch to lib - asio"
   cd libs/asio
-  git apply $ZOPEN_ROOT/boostPatches/asio.patch
+  apply_patch "$ZOPEN_ROOT/boostPatches/asio.patch"
   cd -
 
   # math directory  patch -> located at ./boost/libs/math
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/math.patch"
+  echo "In ZOPEN_INIT, applying patch to lib - math"
   cd libs/math
-  git apply $ZOPEN_ROOT/boostPatches/math.patch
+  apply_patch "$ZOPEN_ROOT/boostPatches/math.patch"
   cd -
 
   # multiprecision directory  patch -> located at ./boost/libs/multiprecision
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/multiprecision.patch"
+  echo "In ZOPEN_INIT, applying patch to lib - multiprecision"
   cd libs/multiprecision
-  git apply $ZOPEN_ROOT/boostPatches/multiprecision.patch
+  apply_patch "$ZOPEN_ROOT/boostPatches/multiprecision.patch"
   cd -
 
   # thread directory  patch -> located at ./boost/libs/thread
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/thread.patch"
+  echo "In ZOPEN_INIT, applying patch to lib - thread"
   cd libs/thread
-  git apply $ZOPEN_ROOT/boostPatches/thread.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/thread_data.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/pthread_helpers.hpp.patch
+  apply_patch "$ZOPEN_ROOT/boostPatches/thread.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/thread_data.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/pthread_helpers.hpp.patch"
   cd -
 
   # build directory  patch -> located at ./boost/tools/build
-  echo "In ZOPEN_INIT, applying patch to $ZOPEN_ROOT/boostPatches/build.patch"
+  echo "In ZOPEN_INIT, applying patch to tools/build"
   cd tools/build/
-  git apply $ZOPEN_ROOT/boostPatches/src_engine.patch
-  git apply $ZOPEN_ROOT/boostPatches/gcc.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/toolset.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/clang.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/intel-linux.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/pathscale.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/pgi.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/vacpp.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/xlcpp.jam.patch
-  git apply $ZOPEN_ROOT/boostPatches/clang-linux-3.9.0.py.patch
-  git apply $ZOPEN_ROOT/boostPatches/gcc-4.8.3-linux.py.patch
+  apply_patch "$ZOPEN_ROOT/boostPatches/src_engine.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/gcc.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/toolset.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/clang.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/intel-linux.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/pathscale.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/pgi.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/vacpp.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/xlcpp.jam.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/clang-linux-3.9.0.py.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/gcc-4.8.3-linux.py.patch"
   cd -
-  
+
   cd ./libs/iostreams
-  git apply $ZOPEN_ROOT/boostPatches/iostreams.Jamfile.v2.patch
+  echo "In ZOPEN_INIT, applying patch to lib - iostreams"
+  apply_patch "$ZOPEN_ROOT/boostPatches/iostreams.Jamfile.v2.patch"
   cd -
 
   cd ./libs/chrono
-  git apply $ZOPEN_ROOT/boostPatches/chrono.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/chrono_io.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/time_point_io.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/runtime_resolution.cpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/time_point_io.hpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/duration_duration_fail.cpp.patch
-  git apply $ZOPEN_ROOT/boostPatches/system_clocks.hpp.patch
+  echo "In ZOPEN_INIT, applying patch to lib - chrono"
+  apply_patch "$ZOPEN_ROOT/boostPatches/chrono.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/chrono_io.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/time_point_io.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/runtime_resolution.cpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/time_point_io.hpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/duration_duration_fail.cpp.patch"
+  apply_patch "$ZOPEN_ROOT/boostPatches/system_clocks.hpp.patch"
   cd -
 
   cd ./libs/test
-  git apply $ZOPEN_ROOT/boostPatches/execution_monitor.ipp.patch
+  echo "In ZOPEN_INIT, applying patch to lib - test framework"
+  apply_patch "$ZOPEN_ROOT/boostPatches/execution_monitor.ipp.patch"
   cd -
 
   cd ./libs/filesystem
-  git apply $ZOPEN_ROOT/boostPatches/directory.cpp.patch 
+  echo "In ZOPEN_INIT, applying patch to lib - filesystem"
+  apply_patch "$ZOPEN_ROOT/boostPatches/directory.cpp.patch"
   cd -
 
   echo `pwd`
